// projects/web-react-redux/src/modules/stage/views/Main.tsx
import React from 'react';
import {Provider} from 'react-redux';
import {connectRedux, LoadingState} from '@clux/react-web';
import {LoadView, RouteParams, APPState} from '@/Global';
import LoadingPanel from '../components/LoadingPanel';
import {CurUser} from '../entity';
import '../assets/css/iconfont.css';
import '../assets/css/global.module.less';

const MainLayout = LoadView('mainLayout', 'main');

interface StoreProps {
  globalLoading?: LoadingState;
  curUser: CurUser;
  subView: RouteParams;
}
interface OwnerProps {}
interface DispatchProps {}

const Component: React.FC<StoreProps & DispatchProps & OwnerProps> = ({globalLoading, subView}) => {
  return (
    <>
      {subView.mainLayout && <MainLayout />}
      <LoadingPanel loadingState={globalLoading} />
    </>
  );
};

function mapStateToProps(appState: APPState): StoreProps {
  return {subView: appState.route.params, curUser: appState.stage.curUser, globalLoading: appState.stage.loading?.global};
}

const APP = connectRedux(mapStateToProps)(React.memo(Component));

export default function Root({store}) {
  return (
    <Provider store={store}>
      <APP />
    </Provider>
  );
}

// projects/web-vue-vuex/src/modules/stage/views/Main.vue
<template>
  <MainLayout v-if="!!subView.mainLayout" />
  <LoadingPanel :loading-state="globalLoading" />
</template>

<script lang="ts">
import {LoadingState, defineView} from '@clux/vue-web';
import {LoadView, RouteParams} from '@/Global';
import LoadingPanel from '../components/LoadingPanel.vue';
import {CurUser} from '../entity';
import '../assets/css/iconfont.css';
import '../assets/css/global.module.less';

const MainLayout = LoadView('mainLayout', 'main');

export default defineView({
  name: 'App',
  components: {
    LoadingPanel,
    MainLayout,
  },
  computed: {
    globalLoading(): LoadingState | undefined {
      return this.$store.state.stage.loading?.global;
    },
    subView(): RouteParams {
      return this.$store.state.route.params;
    },
    curUser(): CurUser {
      return this.$store.state.stage.curUser;
    },
  },
});
</script>

<style lang="less">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
