// projects/web-react-redux/src/modules/photo/views/Main.tsx
import React from 'react';
import {Dispatch, connectRedux} from '@clux/react-web';
import {APPState} from '@/APP';
import List from './List';
import Detail from './Detail';
import {ListView, ItemView, ItemDetail} from '../entity';

// const Test: React.FC<{msg: string}> = ({msg}) => {
//   return <div>test{msg}</div>;
// };

// function loadView() {
//   return (props: {msg: string}) => {
//     return (
//       <Suspense fallback="null">
//         <Test {...props} />
//       </Suspense>
//     );
//   };
// }

// const LoadTest = loadView();

export interface StoreProps {
  listView: ListView;
  itemView: ItemView;
  itemDetail?: ItemDetail;
}
export interface OwnerProps {}
export interface DispatchProps {
  dispatch: Dispatch;
}

const Component: React.FC<StoreProps & DispatchProps & OwnerProps> = ({listView, itemView, itemDetail, dispatch}) => {
  return (
    <>
      {listView === 'list' && <List />}
      {itemView === 'detail' && itemDetail && <Detail dispatch={dispatch} itemDetail={itemDetail} />}
    </>
  );
};

function mapStateToProps(appState: APPState): StoreProps {
  const {listView, itemView, itemDetail} = appState.photo;
  return {listView, itemView, itemDetail};
}

export default connectRedux(mapStateToProps)(React.memo(Component));

// projects/web-vue-vuex/src/modules/photo/views/Main.vue
<template>
  <List v-if="listView === 'list'" />
</template>

<script lang="ts">
import {defineView} from '@clux/vue-web';
import {ListView, ItemView, ItemDetail} from '../entity';
import List from './List.vue';

export default defineView({
  components: {List},
  computed: {
    listView(): ListView {
      return this.$store.state.photo.listView;
    },
    itemView(): ItemView {
      return this.$store.state.photo.itemView;
    },
    itemDetail(): ItemDetail | undefined {
      return this.$store.state.photo.itemDetail;
    },
  },
});
</script>
