// projects/web-react-redux/src/modules/stage/views/Main.tsx
import React from 'react';
import {Provider} from 'react-redux';
import {connectRedux, LoadingState} from '@clux/react-web';
import {LoadView, RouteParams, APPState} from '@/Global';
import LoadingPanel from '../components/LoadingPanel';
import {CurUser} from '../entity';
import '../assets/css/iconfont.css';
import '../assets/css/global.module.less';

const MainLayout = LoadView('mainLayout', 'main');

interface StoreProps {
  globalLoading?: LoadingState;
  curUser: CurUser;
  subView: RouteParams;
}
interface OwnerProps {}
interface DispatchProps {}

const Component: React.FC<StoreProps & DispatchProps & OwnerProps> = ({globalLoading, subView}) => {
  return (
    <>
      {subView.mainLayout && <MainLayout />}
      <LoadingPanel loadingState={globalLoading} />
    </>
  );
};

function mapStateToProps(appState: APPState): StoreProps {
  return {subView: appState.route.params, curUser: appState.stage.curUser, globalLoading: appState.stage.loading?.global};
}

const APP = connectRedux(mapStateToProps)(React.memo(Component));

export default function Root({store}) {
  return (
    <Provider store={store}>
      <APP />
    </Provider>
  );
}

// projects/web-vue-vuex/src/modules/mainLayout/views/Main.vue
<template>
  <NavBar title="相册" />
  <div :class="$style.root">
    <photo v-if="subView.photo" />
  </div>
  <TabBar />
</template>

<script lang="ts">
import {defineView} from '@clux/vue-web';
import {RouteParams, LoadView} from '@/Global';
import NavBar from '@stage/components/NavBar.vue';
import TabBar from './TabBar.vue';

const Photo = LoadView('photo', 'main');

export default defineView({
  components: {
    NavBar,
    TabBar,
    Photo,
  },
  computed: {
    subView(): RouteParams {
      return this.$store.state.route.params;
    },
  },
});
</script>
<style lang="less" module>
:global {
  :local(.root) {
    flex: 1;
    overflow-x: hidden;
    height: 100%;
  }
}
</style>
